

package com.ibm.mobileappbuilder.try20161001082337.ds;
import java.net.URL;
import ibmmobileappbuilder.util.StringUtils;
import com.ibm.mobileappbuilder.try20161001082337.R;
import java.util.ArrayList;
import java.util.List;
import ibmmobileappbuilder.util.StringUtils;

// DatacsvDSSchemaItem static data
public class DatacsvDSItems{

    public static List<DatacsvDSSchemaItem> ITEMS = new ArrayList<DatacsvDSSchemaItem>();
    static {
        // Add items.
        DatacsvDSSchemaItem item;
        item = new DatacsvDSSchemaItem();
        item.name = "Cauliflower";
        item.dataField0 = "ne serving of cauliflower contains 77 percent of the recommended daily value of vitamin C. It's also a good source of vitamin K, protein, thiamin, riboflavin, niacin, magnesium, phosphorus, fiber, vitamin B6, folate, pantothenic acid, potassium, and manganese";
        item.category = "Vegetables";
        item.price = new Double("7.95");
        item.rating = "★★★☆☆";
        item.picture = R.drawable.jpg_e79614sy0r;
        item.webaddress = "http://www.amazon.in/Indian-Gardening-Cauliflower-Summer-Vegetable/dp/B00IRZNMHI?tag=googinhydr18418-21&tag=googinkenshoo-21&ascsubtag=ec5aecf9-4f8e-4a47-ad70-b3b4cc91d337";
        item.id = "57ef73019d17e00300d4dd89";
        addItem(item);
        item = new DatacsvDSSchemaItem();
        item.picture = R.drawable.jpg_a2dzuu4pch;
        item.rating = "★★★★★";
        item.price = new Double("9.95");
        item.category = "Vegetables";
        item.dataField0 = "rinjals too are great for your heart. Being rich in fiber, potassium, vitamin B-6 and phytonutrients like flavonoids, this vegetable lowers the risk of heart disease";
        item.name = "Brinjal";
        item.webaddress = "http://www.naturesbasket.co.in/Products/Brinjal-Small/4827_0_0_0?gclid=CjwKEAjwvb2_BRCb_s7Yo7_ZlHASJABz6L0jCUupR68ILeubcve7wFvz1JBU0b8evvlCpFK9PO-aoBoCLirw_wcB";
        item.id = "57ef73019d17e00300d4dd8a";
        addItem(item);
        item = new DatacsvDSSchemaItem();
        item.picture = R.drawable.jpg_p9iduvry7t;
        item.rating = "★★★★☆";
        item.price = new Double("15.75");
        item.category = "Vegetables";
        item.dataField0 = "High fiber content: The dietary fiber content of an Okra/lady finger is known to be high and hence many health specialists recommend it for digestive benefits.";
        item.name = "ladiesFinger";
        item.webaddress = "http://www.bigbasket.com/pd/10000142/fresho-ladies-finger-1-kg/";
        item.id = "57ef73019d17e00300d4dd8b";
        addItem(item);
        item = new DatacsvDSSchemaItem();
        item.webaddress = "http://www.bigbasket.com/pd/20001088/fresho-apple-royal-gala-6-pcs/?nc=as";
        item.name = "Apple";
        item.dataField0 = "Apples are extremely rich in important antioxidants, flavanoids, and dietary fiber. The phytonutrients and antioxidants in apples may help reduce the risk of developing cancer, hypertension, diabetes, and heart disease";
        item.category = "Fruits";
        item.price = new Double("149.99");
        item.rating = "★★★★★";
        item.picture = R.drawable.jpg_crc9nbhi78;
        item.id = "57ef73019d17e00300d4dd8c";
        addItem(item);
        item = new DatacsvDSSchemaItem();
        item.webaddress = "http://www.naturesbasket.co.in/Products/Banana-Elaichi/4730_0_0_0";
        item.name = "bannana";
        item.dataField0 = "hey contain several essential nutrients, and have benefits for digestion, heart health and weight loss.\n\nAside from being very nutritious, they are also a highly convenient snack food.";
        item.category = "Fruits";
        item.price = new Double("98.55");
        item.rating = "★★★☆☆";
        item.picture = R.drawable.jpg_0u7p7yyvfg;
        item.id = "57ef73019d17e00300d4dd8d";
        addItem(item);
        item = new DatacsvDSSchemaItem();
        item.webaddress = "http://www.naturesbasket.co.in/Products/Pineapple/5670_0_0_0";
        item.name = "pineapple";
        item.dataField0 = "Pineapple,Aside from the interesting story and appearance of this fruit, it is also a storehouse of huge health benefits due to its wealth of nutrients, vitamins, and minerals";
        item.category = "Fruits";
        item.price = new Double("56.52");
        item.rating = "★★★★★";
        item.picture = R.drawable.jpg_gkzaiyyczu;
        item.id = "57ef73019d17e00300d4dd8e";
        addItem(item);
        item = new DatacsvDSSchemaItem();
        item.picture = R.drawable.jpg_axkdamhobb;
        item.rating = "★★★★☆";
        item.price = new Double("40");
        item.category = "Groceries";
        item.dataField0 = "Sona masoori is a type of Indian white rice, mostly grown in the areas of Andra Pradesh and Karnataka in India, according to the Spices of India website. It is a medium-grain, aromatic rice that is lightweight and low in starch. Sona masoori is typically used in dishes such as sweet pongal, biryani, idlis and fried rice";
        item.name = "Rice Sona Masoori";
        item.webaddress = "http://www.amazon.in/Agro-Fresh-Premium-Sona-Rice/dp/B01L22ZA36?tag=googinhydr18418-21";
        item.id = "57ef73019d17e00300d4dd8f";
        addItem(item);
        item = new DatacsvDSSchemaItem();
        item.picture = R.drawable.jpg_qjnhsfawww;
        item.rating = "★★★☆☆";
        item.price = new Double("55.55");
        item.category = "Groceries";
        item.dataField0 = "Whole grains are packed with nutrients, including protein, fiber, B vitamins, antioxidants, and trace minerals (iron, zinc, copper, and magnesium). A diet rich in whole grains has been shown to reduce the risk of heart disease, type 2 diabetes, obesity, and some forms of cancer.";
        item.name = "Whole Wheat";
        item.webaddress = "http://www.amazon.in/24-Mantra-Organic-Wheat-Daliya/dp/B00L926CUU?tag=googinhydr18418-21&tag=googinkenshoo-21&ascsubtag=ec5aecf9-4f8e-4a47-ad70-b3b4cc91d337";
        item.id = "57ef73019d17e00300d4dd90";
        addItem(item);
        item = new DatacsvDSSchemaItem();
        item.picture = R.drawable.jpg_h8mjqoghgb;
        item.rating = "★★★★★";
        item.price = new Double("65.85");
        item.category = "Cleaning";
        item.dataField0 = "New Colin Glass Cleaner with the power of shine boosters not only removes dirt and dust but also gives \"2 times more shine\"than regular cleaners across glass and shiny surfaces\nSuitable for cleaning: Glass and shiny surfaces like, mirrors, glass windows, fridge, TV, oven, kitchen cabinets, furniture";
        item.name = "Colin";
        item.webaddress = "https://www.aaramshop.com/product-detail/colin-more-shine-glass-cleaner-500ml?gclid=CjwKEAjwvb2_BRCb_s7Yo7_ZlHASJABz6L0jzvqIIaFGoxS_rsgljj_iCMRiidp0W_3SbqEawD-S_hoCfkvw_wcB";
        item.id = "57ef73019d17e00300d4dd91";
        addItem(item);
        item = new DatacsvDSSchemaItem();
        item.picture = R.drawable.jpg_t1as10uxmk;
        item.rating = "★★★☆☆";
        item.price = new Double("5.25");
        item.category = "Cleaning";
        item.dataField0 = "Vim Bar has the power of 100 lemons, which helps clean tough grease the fastest\nIt has a unique patented plastic coating at the bottom of the bar which helps prevent it from sogging quickly.";
        item.name = "Vim Bar";
        item.webaddress = "http://www.amazon.in/Vim-Bar-Poly-200-g/dp/B01CJW72OI?tag=googinhydr18418-21&tag=googinkenshoo-21&ascsubtag=ec5aecf9-4f8e-4a47-ad70-b3b4cc91d337";
        item.id = "57ef73019d17e00300d4dd92";
        addItem(item);
        item = new DatacsvDSSchemaItem();
        item.picture = R.drawable.jpg_8nbzqphnzg;
        item.rating = "★★★☆☆";
        item.price = new Double("100.25");
        item.category = "Cleaning";
        item.dataField0 = "Wondering how you can get 100% tough stain removal? Just #PourRubPour and let Surf Excel Matic liquid detergent do the trick.";
        item.name = "Surf Excel";
        item.webaddress = "http://www.amazon.in/Surf-Excel-Quick-Detergent-Powder/dp/B00U2DUE1A?tag=googinhydr18418-21&tag=googinkenshoo-21&ascsubtag=ec5aecf9-4f8e-4a47-ad70-b3b4cc91d337";
        item.id = "57ef73019d17e00300d4dd93";
        addItem(item);
        item = new DatacsvDSSchemaItem();
        item.picture = R.drawable.jpg_aemvdxl4qc;
        item.rating = "★★★☆☆";
        item.price = new Double("179.95");
        item.category = "Cleaning";
        item.dataField0 = "Here's a top stain removal tip for clothes: To keep your whites white for longer, put Vanish Oxi Action Crystal White Gel into your wash to remove the stain. Try and treat the stain as soon as you can, to avoid a dried in stain.\nProduct Description";
        item.name = "Vanish";
        item.webaddress = "http://www.amazon.in/Vanish-Liquid-500-ml/dp/B00PVQK7KG?tag=googinhydr18418-21&tag=googinkenshoo-21&ascsubtag=ec5aecf9-4f8e-4a47-ad70-b3b4cc91d337";
        item.id = "57ef73019d17e00300d4dd94";
        addItem(item);
        item = new DatacsvDSSchemaItem();
        item.webaddress = "http://www.naturesbasket.co.in/Products/Kaffir-Lime-Makroot-Leaves---Exotic/5332_0_0_0";
        item.name = "Pudina";
        item.dataField0 = "The health benefits of mint include the following: Digestion: Mint is a great appetizer or palate cleanser, and it promotes digestion";
        item.category = "Greens";
        item.price = new Double("0.5");
        item.rating = "★★★★★";
        item.picture = R.drawable.jpg_tc5jamgrp0;
        item.id = "57ef73019d17e00300d4dd95";
        addItem(item);
        item = new DatacsvDSSchemaItem();
        item.webaddress = "http://www.naturesbasket.co.in/Products/Spinach-Palak/5815_0_0_0";
        item.name = "Palak";
        item.dataField0 = "Spinach is packed with nutrients like antioxidants, vitamins, omega 3 fatty acids and folic acid which are great for your heart";
        item.category = "Greens";
        item.price = new Double("0.75");
        item.rating = "★★★★☆";
        item.picture = R.drawable.jpg_dkszshbcn5;
        item.id = "57ef73019d17e00300d4dd96";
        addItem(item);
        item = new DatacsvDSSchemaItem();
        item.picture = R.drawable.jpg_ilaa2hzpwb;
        item.rating = "★★★★★";
        item.price = new Double("1");
        item.category = "Greens";
        item.dataField0 = "Coriander,s a wonderful source of dietary fiber, manganese, iron and magnesium";
        item.name = "coriander";
        item.webaddress = "http://www.bigbasket.com/pd/40005796/fresho-coriander-leaves-100-gm/?nc=as";
        item.id = "57ef73019d17e00300d4dd97";
        addItem(item);
        item = new DatacsvDSSchemaItem();
        item.picture = R.drawable.jpg_kbjiucjt3j;
        item.rating = "★★★☆☆";
        item.price = new Double("0.72");
        item.category = "Greens";
        item.dataField0 = "curry leaves,help your heart function better, fights infections and can enliven your hair and skin with vitality";
        item.name = "Curry Leaves";
        item.webaddress = "http://www.bigbasket.com/pd/10000104/fresho-curry-leaves-100-gm/?nc=as";
        item.id = "57ef73019d17e00300d4dd98";
        addItem(item);
    }
    public static void addItem(DatacsvDSSchemaItem item) {
        ITEMS.add(item);
    }
}


